name = "MRiscX"
version = "0.1.0-v4.26.0-rc2"
defaultTargets = ["mriscx"]

[[lean_lib]]
name = "MRiscX"

[[lean_exe]]
name = "mriscx"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"