name = "MRiscX"
version = "0.1.0"
defaultTargets = ["mriscx"]

[[lean_lib]]
name = "MRiscX"

[[lean_exe]]
name = "mriscx"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0-rc1"